In [364]:
import tensorflow as tf
import numpy as np

#  Initialize the Variables required.

In [365]:
X1=tf.Variable(initial_value=[0.,1.,0.,1.])
X2=tf.Variable(initial_value=[0.,0.,1.,1.])
Y_AND=tf.Variable(initial_value=[0.,0.,0.,1.])
Y_NOR=tf.Variable(initial_value=[1.,0.,0.,0.])
Y_OR=tf.Variable(initial_value=[0.,1.,1.,1.])
Y_XOR=tf.Variable(initial_value=[0.,1.,1.,0.])
Y_XNOR=tf.Variable(initial_value=[1.,0.,0.,1.])

In [394]:
# At First we will find weights for AND,OR and NOR Gates

In [395]:
#Let us define the model

In [396]:
class Model(object):
 
   def __init__(self):
        
         # Initialize the weights to `2.0` and the bias to `2.0`
         # In practice, these should be initialized to random values
         # self.W1=tf.random.normal([1])
        self.W1 = tf.Variable(2.)
        self.W2= tf.Variable(2.)
        self.b=tf.Variable(2.)
   
   def __call__(self, x1,x2):
        self.K1=self.W1 * x1 + self.W2 * x2 + self.b
        self.Output = tf.keras.activations.sigmoid(self.K1)
        return(self.Output)
model=Model()

In [397]:
#Cost function will be

In [398]:
def compute_cost(target_y, predicted_y):
    c=tf.keras.losses.BinaryCrossentropy()
    return(c(target_y,predicted_y))

In [399]:
def None_to_Zero(v):
    if v==None:
        v=0
    return v

In [400]:
def train(model, X1, X2, Y2, learning_rate):
    with tf.GradientTape() as t:
            current_loss = compute_cost(Y2,model(X1,X2))
    dW1,dW2,db=t.gradient(current_loss,[model.W1,model.W2,model.b])          
    dW1=None_to_Zero(dW1)
    db=None_to_Zero(db)
    dW2=None_to_Zero(dW2)
    model.W1.assign_sub(learning_rate * dW1)
    model.b.assign_sub(learning_rate * db)
    model.W2.assign_sub(learning_rate * dW2)

# For AND Gate

In [401]:
# As we have very less Input data we need to increase the number of # epochs or the learning rate. 
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
    train(model, X1, X2,Y_AND, learning_rate)
   # train(model, X1, X2,Y_NOR, learning_rate)
   # train(model, X1, X2,Y_OR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

[0. 0. 0. 1.]


In [402]:
W_AND={'W1':model.W1.numpy(),'W2':model.W2.numpy(),'b':model.b.numpy()}

In [403]:
model.b

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-4.9358997>

In [404]:
#W_AND={'W1':3.1480012,'W2':3.1480012,'b':-4.9358997}

In [405]:
W_AND

{'W1': 3.1480012, 'W2': 3.1480012, 'b': -4.9358997}

# For OR Gate

In [406]:
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
    train(model, X1, X2,Y_OR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

[0. 1. 1. 1.]


In [407]:
W_OR={'W1':model.W1.numpy(),'W2':model.W2.numpy(),'b':model.b.numpy()}

In [408]:
W_OR

{'W1': 5.6196923, 'W2': 5.6196923, 'b': -2.3270602}

# For NOR Gate

In [409]:
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
    train(model, X1, X2,Y_NOR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

[1. 0. 0. 0.]


In [410]:
W_NOR={'W1':model.W1.numpy(),'W2':model.W2.numpy(),'b':model.b.numpy()}

In [411]:
model.b.numpy()

0.94292766

In [412]:
# W_NOR={'W1':-3.0863311,'W2':-3.0863311,'b':0.94292766}

In [413]:
W_NOR

{'W1': -3.0863311, 'W2': -3.0863311, 'b': 0.94292766}

# Model for XOR Gate

In [414]:
class Model_XOR(object):
    
 
    def __init__(self):
        self.W11 = tf.Variable(W_AND['W1'])
        self.W12= tf.Variable(W_AND['W2'])
        self.b13=tf.Variable(W_AND['b'])
        self.W14 = tf.Variable(W_NOR['W1'])
        self.W15= tf.Variable(W_NOR['W2'])
        self.b16=tf.Variable(W_NOR['b'])
        self.W21 = tf.Variable(W_NOR['W1'])
        self.W22= tf.Variable(W_NOR['W2'])
        self.b23=tf.Variable(W_NOR['b'])

    def __call__(self, x1,x2):
        self.W1=self.W11 * x1 + self.W12*x2 + self.b13
        self.W2=self.W14 * x1 + self.W15*x2 + self.b16
        self.A1 = tf.keras.activations.sigmoid(self.W1)
        self.A2 = tf.keras.activations.sigmoid(self.W2)
        self.W3=self.W21 * self.A1 + self.W22*self.A2 + self.b23
        self.A3 = tf.keras.activations.sigmoid(self.W3)
        return(self.A3)
model_xor=Model_XOR()

In [415]:
model_xor.W14

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-3.0863311>

In [416]:
def train_xor(model_xor, X1, X2, Y2, learning_rate):
    with tf.GradientTape() as t:
        current_loss = compute_cost(Y2,model_xor(X1,X2))
            
 
    dW11,dW12,db13,dW14,dW15,db16,dW21,dW22,db23=t.gradient(current_loss,[model_xor.W11,model_xor.W12,model_xor.b13,
                                                                            model_xor.W14,model_xor.W15,model_xor.b16,
                                                                            model_xor.W21,model_xor.W22,model_xor.b23,])
    
 
    model_xor.W11.assign_sub(learning_rate * None_to_Zero(dW11))
    model_xor.b13.assign_sub(learning_rate * None_to_Zero(db13))
    model_xor.W12.assign_sub(learning_rate * None_to_Zero(dW12))
    model_xor.W14.assign_sub(learning_rate * None_to_Zero(dW14))
    model_xor.b16.assign_sub(learning_rate * None_to_Zero(db16))
    model_xor.W15.assign_sub(learning_rate * None_to_Zero(dW15))
    model_xor.W21.assign_sub(learning_rate * None_to_Zero(dW21))
    model_xor.b23.assign_sub(learning_rate * None_to_Zero(db23))
    model_xor.W22.assign_sub(learning_rate * None_to_Zero(dW22))

In [417]:
epochs=range(100)
learning_rate=0.1
for epoch in epochs:
    train_xor(model_xor, X1, X2,Y_XOR, learning_rate)
   #Once the training is done we can find results by calling the Model_XOR  #Class object as 
print(np.round(model_xor(X1, X2).numpy()))

[0. 1. 1. 0.]


In [418]:
model_xor(X1, X2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.27440244, 0.6892559 , 0.6892559 , 0.2543708 ], dtype=float32)>

# Model for XNOR Gate  

In [419]:
class Model_XNOR(object):
    
 
    def __init__(self):
        self.W11 = tf.Variable(W_AND['W1'])
        self.W12= tf.Variable(W_AND['W2'])
        self.b13=tf.Variable(W_AND['b'])
        self.W14 = tf.Variable(W_NOR['W1'])
        self.W15= tf.Variable(W_NOR['W2'])
        self.b16=tf.Variable(W_NOR['b'])
        self.W21 = tf.Variable(W_OR['W1'])
        self.W22= tf.Variable(W_OR['W2'])
        self.b23=tf.Variable(W_OR['b'])

    def __call__(self, x1,x2):
        self.W1=self.W11 * x1 + self.W12*x2 + self.b13
        self.W2=self.W14 * x1 + self.W15*x2 + self.b16
        self.A1 = tf.keras.activations.sigmoid(self.W1)
        self.A2 = tf.keras.activations.sigmoid(self.W2)
        self.W3=self.W21 * self.A1 + self.W22*self.A2 + self.b23
        self.A3 = tf.keras.activations.sigmoid(self.W3)
        return(self.A3)
model_xnor=Model_XNOR()

In [420]:
def train_xnor(model_xnor, X1, X2, Y2, learning_rate):
    with tf.GradientTape() as t:
        current_loss = compute_cost(Y2,model_xnor(X1,X2))
            
 
    dW11,dW12,db13,dW14,dW15,db16,dW21,dW22,db23=t.gradient(current_loss,[model_xnor.W11,model_xnor.W12,model_xnor.b13,
                                                                            model_xnor.W14,model_xnor.W15,model_xnor.b16,
                                                                            model_xnor.W21,model_xnor.W22,model_xnor.b23,])
    
 
    model_xnor.W11.assign_sub(learning_rate * None_to_Zero(dW11))
    model_xnor.b13.assign_sub(learning_rate * None_to_Zero(db13))
    model_xnor.W12.assign_sub(learning_rate * None_to_Zero(dW12))
    model_xnor.W14.assign_sub(learning_rate * None_to_Zero(dW14))
    model_xnor.b16.assign_sub(learning_rate * None_to_Zero(db16))
    model_xnor.W15.assign_sub(learning_rate * None_to_Zero(dW15))
    model_xnor.W21.assign_sub(learning_rate * None_to_Zero(dW21))
    model_xnor.b23.assign_sub(learning_rate * None_to_Zero(db23))
    model_xnor.W22.assign_sub(learning_rate * None_to_Zero(dW22))

In [421]:
epochs=range(100)
learning_rate=0.1
for epoch in epochs:
    train_xnor(model_xnor, X1, X2,Y_XNOR, learning_rate)
   #Once the training is done we can find results by calling the Model_XOR  #Class object as 
print(np.round(model_xnor(X1, X2).numpy()))

[1. 0. 0. 1.]
